name: Generate Embeddings

on:
  push:
    branches:
      - main
    paths:
      - 'knowledge/**.mdx'
      - 'scripts/generate_embeddings.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar el script
      - name: Run embeddings script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/generate_embeddings.js